import copy
import datetime

from django.core.exceptions import FieldError
from django.db.models.constants import LOOKUP_SEP
from django.db.models import fields
from django.db.models.query_utils import refs_aggregate
from django.utils.functional import cached_property


class ExpressionNode(object):
    """
    Base class for all query expressions.
    """

    # Arithmetic connectors
    ADD = '+'
    SUB = '-'
    MUL = '*'
    DIV = '/'
    POW = '^'
    # The following is a quoted % operator - it is quoted because it can be
    # used in strings that also have parameter substitution.
    MOD = '%%'

    # Bitwise operators - note that these are generated by .bitand()
    # and .bitor(), the '&' and '|' are reserved for boolean operator
    # usage.
    BITAND = '&'
    BITOR = '|'

    # aggregate specific fields
    is_aggregate = False
    is_summary = False
    # resolve_aggregate uses below to coerce
    is_ordinal = False
    is_computed = False

    def __init__(self, output_type=None):
        self.col = None
        self.source = output_type

    def _combine(self, other, connector, reversed, node=None):
        if isinstance(other, datetime.timedelta):
            return DateModifierNode(self, connector, other)

        if not isinstance(other, ExpressionNode):
            # everything must be some kind of ExpressionNode, so Value is the fallback
            other = Value(other)

        if reversed:
            return Expression(other, connector, self)
        return Expression(self, connector, other)

    def as_sql(self, compiler, connection):
        """
        Responsible for returning a (sql, [params]) tuple to be included
        in the current query.

        Different backends can provide their own implementation, by
        providing an `as_{vendor}` method, and patching the Expression:

        ```
        def override_as_sql(self, compiler, connection):
            print('override')
            return super(ExpressionNode, self).as_sql(compiler, connection)
        setattr(ExpressionNode, 'as_' + connection.vendor, override_as_sql)
        ```

        Arguments:
         * compiler: the query compiler responsible for generating the query.
           Must have a compile method, returning a (sql, [params]) tuple.
           Calling compiler(value) will return a quoted `value`

         * connection: the database connection used for the current query

        Returns: (sql, params)
          Where `sql` is a string containing ordered sql parameters to be
          replaced with the elements of the list `params`
        """
        raise NotImplementedError("Subclasses must implement as_sql()")

    def prepare(self, query=None, allow_joins=True, reuse=None, summarise=False):
        """
        Provides the chance to do any preprocessing or validation before being
        added to the query.

        Arguments:
         * query: the backend query implementation
         * allow_joins: boolean allowing or denying use of joins
           in this query
         * reuse: a set of reusable joins for multijoins
         * summarise: a terminal aggregate clause

        Returns: self
        """
        self.is_summary = summarise
        return self

    @property
    def field(self):
        return self.output_type

    @cached_property
    def output_type(self):
        self._resolve_source()
        return self.source

    def _resolve_source(self):
        if self.source is None:
            sources = self.get_sources()
            num_sources = len(sources)
            if num_sources == 0:
                raise FieldError("Cannot resolve expression type, unknown output_type")
            elif num_sources == 1:
                self.source = sources[0]
            else:
                # this could be smarter by allowing certain combinations
                self.source = sources[0]
                for source in sources:
                    if not isinstance(self.source, source.__class__):
                        raise FieldError(
                            "Expression contains mixed types. You must set output_type")

    def get_lookup(self, lookup):
        return self.output_type.get_lookup(lookup)

    def get_transform(self, name):
        return self.output_type.get_transform(name)

    def relabeled_clone(self, change_map):
        return copy.copy(self)

    def contains_aggregate(self, existing_aggregates):
        return False, ()

    def refs_field(self, aggregate_types, field_types):
        """
        Helper method for check_aggregate_support on backends
        """
        return False

    def prepare_database_save(self, unused):
        return self

    def get_group_by_cols(self):
        if self.col is not None:
            return [self.col]
        return []

    def get_sources(self):
        if self.source is not None:
            return [self.source]
        return []

    def __bool__(self):
        """
        For truth value testing.
        """
        return True

    #############
    # OPERATORS #
    #############

    def __add__(self, other):
        return self._combine(other, self.ADD, False)

    def __sub__(self, other):
        return self._combine(other, self.SUB, False)

    def __mul__(self, other):
        return self._combine(other, self.MUL, False)

    def __truediv__(self, other):
        return self._combine(other, self.DIV, False)

    def __div__(self, other):  # Python 2 compatibility
        return type(self).__truediv__(self, other)

    def __mod__(self, other):
        return self._combine(other, self.MOD, False)

    def __pow__(self, other):
        return self._combine(other, self.POW, False)

    def __and__(self, other):
        raise NotImplementedError(
            "Use .bitand() and .bitor() for bitwise logical operations."
        )

    def bitand(self, other):
        return self._combine(other, self.BITAND, False)

    def __or__(self, other):
        raise NotImplementedError(
            "Use .bitand() and .bitor() for bitwise logical operations."
        )

    def bitor(self, other):
        return self._combine(other, self.BITOR, False)

    def __radd__(self, other):
        return self._combine(other, self.ADD, True)

    def __rsub__(self, other):
        return self._combine(other, self.SUB, True)

    def __rmul__(self, other):
        return self._combine(other, self.MUL, True)

    def __rtruediv__(self, other):
        return self._combine(other, self.DIV, True)

    def __rdiv__(self, other):  # Python 2 compatibility
        return type(self).__rtruediv__(self, other)

    def __rmod__(self, other):
        return self._combine(other, self.MOD, True)

    def __rpow__(self, other):
        return self._combine(other, self.POW, True)

    def __rand__(self, other):
        raise NotImplementedError(
            "Use .bitand() and .bitor() for bitwise logical operations."
        )

    def __ror__(self, other):
        raise NotImplementedError(
            "Use .bitand() and .bitor() for bitwise logical operations."
        )


class Expression(ExpressionNode):

    def __init__(self, lhs, connector, rhs, output_type=None):
        super(Expression, self).__init__(output_type=output_type)
        self.lhs = lhs
        self.rhs = rhs
        self.connector = connector
        self.is_aggregate = self.lhs.is_aggregate or self.rhs.is_aggregate

    def as_sql(self, compiler, connection):
        expressions = []
        expression_params = []
        sql, params = compiler.compile(self.lhs)
        expressions.append(sql)
        expression_params.extend(params)
        sql, params = compiler.compile(self.rhs)
        expressions.append(sql)
        expression_params.extend(params)
        # order of precedence
        expression_wrapper = '(%s)'
        sql = connection.ops.combine_expression(self.connector, expressions)
        return expression_wrapper % sql, expression_params

    def prepare(self, query=None, allow_joins=True, reuse=None, summarise=False):
        self.is_summary = summarise
        self.lhs.prepare(query, allow_joins, reuse, summarise)
        self.rhs.prepare(query, allow_joins, reuse, summarise)
        return self

    @cached_property
    def output_type(self):
        self._resolve_source()
        return self.source

    def relabeled_clone(self, change_map):
        clone = copy.copy(self)
        clone.lhs = self.lhs.relabeled_clone(change_map)
        clone.rhs = self.rhs.relabeled_clone(change_map)
        return clone

    def contains_aggregate(self, existing_aggregates):
        for node in (self.lhs, self.rhs):
            agg, lookup = node.contains_aggregate(existing_aggregates)
            if agg:
                return agg, lookup
        return False, ()

    def refs_field(self, aggregate_types, field_types):
        """
        Helper method for check_aggregate_support on backends
        """
        return any(
            node.refs_field(aggregate_types, field_types)
            for node in (self.lhs, self.rhs))

    def get_group_by_cols(self):
        return self.lhs.get_group_by_cols() + self.rhs.get_group_by_cols()

    def get_sources(self):
        if self.source is not None:
            return [self.source]
        return [
            source for node in (self.lhs, self.rhs)
            for source in node.get_sources()]


class DateModifierNode(Expression):
    """
    Node that implements the following syntax:
    filter(end_date__gt=F('start_date') + datetime.timedelta(days=3, seconds=200))

    which translates into:
    POSTGRES:
        WHERE end_date > (start_date + INTERVAL '3 days 200 seconds')

    MYSQL:
        WHERE end_date > (start_date + INTERVAL '3 0:0:200:0' DAY_MICROSECOND)

    ORACLE:
        WHERE end_date > (start_date + INTERVAL '3 00:03:20.000000' DAY(1) TO SECOND(6))

    SQLITE:
        WHERE end_date > django_format_dtdelta(start_date, "+" "3", "200", "0")
        (A custom function is used in order to preserve six digits of fractional
        second information on sqlite, and to format both date and datetime values.)

    Note that microsecond comparisons are not well supported with MySQL, since
    MySQL does not store microsecond information.

    Only adding and subtracting timedeltas is supported, attempts to use other
    operations raise a TypeError.
    """
    def __init__(self, lhs, connector, rhs):
        if not isinstance(rhs, datetime.timedelta):
            raise TypeError('rhs must be a timedelta.')
        if connector not in (self.ADD, self.SUB):
            raise TypeError('Connector must be + or -, not %s' % connector)
        super(DateModifierNode, self).__init__(lhs, connector, Value(rhs))

    def as_sql(self, compiler, connection):
        timedelta = self.rhs.value
        sql, params = compiler.compile(self.lhs)
        if (timedelta.days == timedelta.seconds == timedelta.microseconds == 0):
            return sql, params
        return connection.ops.date_interval_sql(sql, self.connector, timedelta), params


class F(ExpressionNode):
    """
    An expression representing the value of the given field.
    """

    def __init__(self, name):
        """
        Arguments:
         * name: the name of the field this expression references
        """
        super(F, self).__init__()
        self.name = name

    def prepare(self, query=None, allow_joins=True, reuse=None, summarise=False):
        self.is_summary = summarise
        if not allow_joins and LOOKUP_SEP in self.name:
            raise FieldError("Joined field references are not permitted in this query")
        self.setup_cols(query, reuse)
        return self

    def as_sql(self, compiler, connection):
        if hasattr(self.col, 'as_sql'):
            return compiler.compile(self.col)
        qn = compiler
        return '%s.%s' % (qn(self.col[0]), qn(self.col[1])), []

    def setup_cols(self, query, reuse):
        if query is None:
            return
        field_list = self.name.split(LOOKUP_SEP)
        if self.name in query.annotations:
            self.col = query.annotation_select[self.name]
        else:
            try:
                field, sources, opts, join_list, path = query.setup_joins(
                    field_list, query.get_meta(),
                    query.get_initial_alias(), reuse)
                self._used_joins = join_list
                targets, _, join_list = query.trim_joins(sources, join_list, path)
                if reuse is not None:
                    reuse.update(join_list)
                for t in targets:
                    source = self.source if self.source is not None else sources[0]
                    self.col = Col(join_list[-1], t, source)
                if self.source is None:
                    self.source = sources[0]
            except fields.FieldDoesNotExist:
                raise FieldError("Cannot resolve keyword %r into field. "
                                 "Choices are: %s" % (self.name,
                                                      [f.name for f in self.opts.fields]))

    def get_group_by_cols(self):
        cols = []
        if isinstance(self.col, tuple):
            cols.append(self.col)
        elif hasattr(self.col, 'get_group_by_cols'):
            cols.extend(self.col.get_group_by_cols())
        return cols

    def get_sources(self):
        return [self.source] if self.source is not None else []

    def contains_aggregate(self, existing_aggregates):
        return refs_aggregate(self.name.split(LOOKUP_SEP), existing_aggregates)

    def relabeled_clone(self, change_map):
        clone = copy.copy(self)
        if hasattr(clone.col, 'relabeled_clone'):
            clone.col = clone.col.relabeled_clone(change_map)
        elif clone.col:
            clone.col = (change_map.get(clone.col[0], clone.col[0]), clone.col[1])
        return clone


class Func(ExpressionNode):
    """
    A SQL function call.
    """
    function = None
    template = '%(function)s(%(expressions)s)'
    arg_joiner = ', '

    def __init__(self, *expressions, **extra):
        output_type = extra.pop('output_type', None)
        super(Func, self).__init__(output_type=output_type)
        self.expressions = self._parse_expressions(*expressions)
        self.extra = extra

    def _parse_expressions(self, *expressions):
        return [
            arg if isinstance(arg, ExpressionNode) else F(arg)
            for arg in expressions
        ]

    def prepare(self, query=None, allow_joins=True, reuse=None, summarise=False):
        self.is_summary = summarise
        for arg in self.expressions:
            arg.prepare(query, allow_joins, reuse, summarise)
        return self

    def as_sql(self, compiler, connection):
        sql_parts = []
        params = []
        for arg in self.expressions:
            arg_sql, arg_params = compiler.compile(arg)
            sql_parts.append(arg_sql)
            params.extend(arg_params)
        self.extra['function'] = self.extra.get('function', self.function)
        self.extra['expressions'] = self.extra['field'] = self.arg_joiner.join(sql_parts)
        template = self.extra.get('template', self.template)
        return template % self.extra, params

    def get_sources(self):
        if self.source is not None:
            return [self.source]
        return [
            source for arg in self.expressions
            for source in arg.get_sources()]

    def contains_aggregate(self, existing_aggregates):
        for arg in self.expressions:
            agg, lookup = arg.contains_aggregate(existing_aggregates)
            if agg:
                return agg, lookup
        return False, ()

    def refs_field(self, aggregate_types, field_types):
        """
        Helper method for check_aggregate_support on backends
        """
        return any(arg.refs_field(aggregate_types, field_types) for arg in self.expressions)

    def relabeled_clone(self, change_map):
        clone = copy.copy(self)
        new_expressions = [
            arg.relabeled_clone(change_map) for arg in clone.expressions]
        clone.expressions = new_expressions
        return clone


class Value(ExpressionNode):
    """
    Represents a wrapped value as a node within an expression
    """

    def __init__(self, value, output_type=None):
        """
        Arguments:
         * value: the value this expression represents. The value will be
           added into the sql parameter list and properly quoted

         * output_type: the Model Field type that this expression will
           return, such as IntegerField() or CharField()
        """
        super(Value, self).__init__(output_type=output_type)
        self.value = value

    def as_sql(self, compiler, connection):
        return '%s', [self.value]


class Col(ExpressionNode):
    def __init__(self, alias, target, source):
        super(Col, self).__init__(output_type=source)
        self.alias, self.target, self.source = alias, target, source

    def as_sql(self, qn, connection):
        return "%s.%s" % (qn(self.alias), qn(self.target.column)), []

    def relabeled_clone(self, relabels):
        return self.__class__(relabels.get(self.alias, self.alias), self.target, self.source)

    def get_group_by_cols(self):
        return [(self.alias, self.target.column)]


class Date(ExpressionNode):
    """
    Add a date selection column.
    """
    def __init__(self, col, lookup_type):
        super(Date, self).__init__(output_type=fields.DateField())
        self.col = col
        self.lookup_type = lookup_type

    def relabeled_clone(self, change_map):
        return self.__class__(
            (change_map.get(self.col[0], self.col[0]), self.col[1]),
            self.lookup_type)

    def as_sql(self, qn, connection):
        if isinstance(self.col, (list, tuple)):
            col = '%s.%s' % tuple(qn(c) for c in self.col)
        else:
            col = self.col
        return connection.ops.date_trunc_sql(self.lookup_type, col), []


class DateTime(ExpressionNode):
    """
    Add a datetime selection column.
    """
    def __init__(self, col, lookup_type, tzname):
        super(DateTime, self).__init__(output_type=fields.DateTimeField())
        self.col = col
        self.lookup_type = lookup_type
        self.tzname = tzname

    def relabeled_clone(self, change_map):
        return self.__class__(
            (change_map.get(self.col[0], self.col[0]), self.col[1]),
            self.lookup_type,
            self.tzname)

    def as_sql(self, qn, connection):
        if isinstance(self.col, (list, tuple)):
            col = '%s.%s' % tuple(qn(c) for c in self.col)
        else:
            col = self.col
        return connection.ops.datetime_trunc_sql(self.lookup_type, col, self.tzname)
